services:
  # 1. Database Service
  postgres:
    image: postgres:15-alpine
    container_name: qlass_db         
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - qlass_postgres_data:/var/lib/postgresql/data
    networks:
      - qlass_network                 

  # 2. GUI Database Manager
  dbgate:
    image: dbgate/dbgate
    container_name: qlass_dbgate
    restart: always
    ports:
      - "5050:3000" 
    volumes:
      - qlass_dbgate_data:/root/.dbgate 
    networks:
      - qlass_network

  # 3. Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: qlass_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - qlass_redis_data:/data
    networks:
      - qlass_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

# 3. Define Volumes
volumes:
  qlass_postgres_data:
  qlass_dbgate_data:
  qlass_redis_data:

networks:
  qlass_network:
    driver: bridge